import type { KnowledgeEntry } from "./catalog-types";

export const KNOWLEDGE_ENTRIES: KnowledgeEntry[] = [
  {
    id: "kn-1",
    title: "LOGO 最小留白与缩放限制",
    topCategory: "brand-vi",
    subTopicId: "logo-rules",
    channels: ["all"],
    industries: ["all"],
    priority: "high",
    summary: "LOGO 四周至少保留 0.5× 字高留白，禁止拉伸变形，深色底使用反白版本。",
    content:
      "## LOGO 使用规范\n\n1. **摆放位置**：主视觉区域左上角或居中偏上，不与促销角标重叠。\n2. **最小留白**：四周至少保留 0.5× 字高空白。\n3. **缩放限制**：等比缩放，宽度不小于画面宽度的 12%。\n4. **禁止变形**：不得倾斜、描边改色或添加阴影。\n5. **配色要求**：浅色底用主色 LOGO，深色底用反白 LOGO。",
    tags: ["LOGO", "留白", "品牌"],
    visibility: "team",
    status: "active",
    createdBy: "品牌管理员",
    createdAt: "2026-03-01 10:00",
    updatedAt: "2026-05-15 14:00",
    usageCount: 342,
    version: 3,
  },
  {
    id: "kn-2",
    title: "品牌官方色值与禁用搭配",
    topCategory: "brand-vi",
    subTopicId: "color-rules",
    channels: ["all"],
    industries: ["all"],
    priority: "high",
    summary: "主色 #FF0036、辅色 #FFD700；禁止与荧光绿、纯黑大面积搭配。",
    content:
      "主色 **#FF0036**（促销红），辅色 **#FFD700**（金色点缀）。\n\n禁用搭配：荧光绿 + 促销红、纯黑背景 + 低对比文案。\n\nAI 生成时需在 prompt 中约束色板范围。",
    tags: ["色值", "配色", "品牌"],
    visibility: "public",
    status: "active",
    createdBy: "品牌管理员",
    createdAt: "2026-03-01 10:05",
    updatedAt: "2026-03-01 10:05",
    usageCount: 520,
    version: 1,
  },
  {
    id: "kn-3",
    title: "官方 Slogan 固定写法",
    topCategory: "brand-vi",
    subTopicId: "copy-tone",
    channels: ["all"],
    industries: ["all"],
    priority: "medium",
    summary: "「省钱神券，领券更划算」为固定 Slogan，禁止改写为极限词表述。",
    content: "固定 Slogan：**省钱神券，领券更划算**\n\n禁用变体：「全网最低」「史上最强」等极限词表述。",
    tags: ["Slogan", "文案口径"],
    visibility: "team",
    status: "active",
    createdBy: "品牌管理员",
    createdAt: "2026-04-10 09:00",
    updatedAt: "2026-04-10 09:00",
    usageCount: 189,
    version: 1,
  },
  {
    id: "kn-4",
    title: "美妆行业正向生成描述词库",
    topCategory: "prompt",
    subTopicId: "industry-prompt",
    channels: ["douyin", "xiaohongshu"],
    industries: ["beauty"],
    priority: "high",
    summary: "柔光棚拍、成分可视化、清新自然场景，突出功效与质感。",
    content:
      "推荐正向词：柔光棚拍、成分可视化、清新自然、低饱和高级灰、功效标注箭头。\n\n场景：浴室梳妆台、阳光窗台前。\n\n避免：过度磨皮、夸张 Before/After。",
    tags: ["美妆", "Prompt", "正向"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小李",
    createdAt: "2026-05-20 11:00",
    updatedAt: "2026-06-01 16:00",
    usageCount: 156,
    version: 2,
  },
  {
    id: "kn-5",
    title: "国潮促销风固定描述句式",
    topCategory: "prompt",
    subTopicId: "style-prompt",
    channels: ["douyin"],
    industries: ["all"],
    priority: "medium",
    summary: "红金配色 + 传统纹样边框 + 大促节点氛围，适合 618/双11。",
    content: "句式模板：「国潮促销风格，红金配色，传统祥云纹样边框，大促氛围，高对比促点击」",
    tags: ["国潮", "促销", "风格"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小张",
    createdAt: "2026-05-25 14:00",
    updatedAt: "2026-05-25 14:00",
    usageCount: 98,
    version: 1,
  },
  {
    id: "kn-6",
    title: "负面规避词库 · 畸形与违禁构图",
    topCategory: "prompt",
    subTopicId: "negative-prompt",
    channels: ["all"],
    industries: ["all"],
    priority: "high",
    summary: "自动屏蔽多指、畸形人脸、裸露、政治敏感元素等违规画面。",
    content:
      "负面词：deformed hands, extra fingers, blurry face, nudity, political symbols, watermark, low quality, text gibberish.\n\n违禁构图：夸大对比、虚假医疗效果暗示。",
    tags: ["负面词", "合规", "安全"],
    visibility: "public",
    status: "active",
    createdBy: "系统",
    createdAt: "2026-01-01 00:00",
    updatedAt: "2026-06-10 09:00",
    usageCount: 2100,
    version: 5,
  },
  {
    id: "kn-7",
    title: "省钱券专项 Prompt 模板",
    topCategory: "prompt",
    subTopicId: "coupon-prompt",
    channels: ["douyin"],
    industries: ["all"],
    priority: "high",
    summary: "突出券后价、捡漏氛围、真实生活场景，避免虚假低价暗示。",
    content:
      "模板：真实生活场景，突出领券后更划算，券后价清晰标注，捡漏氛围但不夸大，信息流竖版构图，转化组件底部居中。\n\n关联素材库：mc-img-6 外投图配置模板。",
    tags: ["省钱券", "捡漏", "Prompt"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小李",
    createdAt: "2026-06-08 10:00",
    updatedAt: "2026-06-18 15:00",
    usageCount: 234,
    version: 4,
  },
  {
    id: "kn-8",
    title: "抖音信息流素材硬性规范",
    topCategory: "channel-rules",
    subTopicId: "platform-spec",
    channels: ["douyin"],
    industries: ["all"],
    priority: "high",
    summary: "竖版 1080×1920，图片 ≤5MB，视频 15–60s，码率建议 8Mbps。",
    content:
      "**尺寸**：1080×1920（9:16）\n**图片**：JPG/PNG，≤5MB\n**视频**：15–60s，MP4，H.264\n**文案**：标题 ≤30 字，避免极限词",
    tags: ["抖音", "尺寸", "规范"],
    visibility: "public",
    status: "active",
    createdBy: "系统",
    createdAt: "2026-01-01 00:00",
    updatedAt: "2026-06-01 00:00",
    usageCount: 890,
    version: 2,
  },
  {
    id: "kn-9",
    title: "广告法极限词与违禁营销话术",
    topCategory: "channel-rules",
    subTopicId: "compliance",
    channels: ["all"],
    industries: ["all"],
    priority: "high",
    summary: "禁用「第一」「最好」「全网最低」等极限词；Healthcare 类需资质说明。",
    content:
      "禁用词库：第一、最好、顶级、全网最低、100% 有效、立即见效……\n\nHealthcare/美妆需标注「效果因人而异」。",
    tags: ["广告法", "极限词", "合规"],
    visibility: "public",
    status: "active",
    createdBy: "系统",
    createdAt: "2026-01-01 00:00",
    updatedAt: "2026-03-15 00:00",
    usageCount: 1500,
    version: 3,
  },
  {
    id: "kn-10",
    title: "抖音跑量素材共性 · 信息流",
    topCategory: "channel-rules",
    subTopicId: "channel-preference",
    channels: ["douyin"],
    industries: ["all"],
    priority: "medium",
    summary: "前 3 秒强钩子、大字价格、真实场景、券后价对比结构跑量更好。",
    content: "跑量共性：痛点提问开场 → 产品特写 → 券后价大字 → 底部 CTA。色调偏暖，信息密度每 3 秒一个点。",
    tags: ["抖音", "跑量", "偏好"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小李",
    createdAt: "2026-06-01 14:00",
    updatedAt: "2026-06-15 10:00",
    usageCount: 67,
    version: 2,
  },
  {
    id: "kn-11",
    title: "3C 品类标准化卖点话术",
    topCategory: "industry-strategy",
    subTopicId: "selling-points",
    channels: ["all"],
    industries: ["3c"],
    priority: "medium",
    summary: "参数可视化、续航/性能对比、开箱质感，避免虚假性能承诺。",
    content: "卖点结构：核心参数 3 条 + 场景化使用 + 价格优势。禁用「永不卡顿」等绝对化表述。",
    tags: ["3C", "卖点", "话术"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小张",
    createdAt: "2026-05-10 09:00",
    updatedAt: "2026-05-10 09:00",
    usageCount: 45,
    version: 1,
  },
  {
    id: "kn-12",
    title: "捡漏专场选品与文案范式",
    topCategory: "industry-strategy",
    subTopicId: "coupon-tactics",
    channels: ["douyin"],
    industries: ["all"],
    priority: "high",
    summary: "券后价 ≤ 原价 5 折、库存 ≤100、近 7 日好评率 ≥95% 为捡漏筛选逻辑。",
    content:
      "选品规则：券后价/原价 ≤ 0.5，库存紧张，好评率高。\n\n文案范式：「券后 ¥XX，比日常省 ¥XX」「限时捡漏，手慢无」。",
    tags: ["捡漏", "选品", "券"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小李",
    createdAt: "2026-06-05 11:00",
    updatedAt: "2026-06-12 09:00",
    usageCount: 178,
    version: 3,
  },
  {
    id: "kn-13",
    title: "划线价与券后价统一描述规则",
    topCategory: "industry-strategy",
    subTopicId: "pricing-copy",
    channels: ["all"],
    industries: ["all"],
    priority: "medium",
    summary: "划线价为近 30 日最低成交价；券后价需标注「领券后」前缀。",
    content: "格式：日常价 ~~¥199~~ → 券后 **¥99**（领券后）。禁止虚构划线价。",
    tags: ["定价", "券后价", "规范"],
    visibility: "public",
    status: "active",
    createdBy: "系统",
    createdAt: "2026-02-01 00:00",
    updatedAt: "2026-02-01 00:00",
    usageCount: 620,
    version: 1,
  },
  {
    id: "kn-14",
    title: "外投图片标准化构图层级",
    topCategory: "structure-paradigm",
    subTopicId: "image-structure",
    channels: ["douyin", "xiaohongshu"],
    industries: ["all"],
    priority: "high",
    summary: "上 1/3 钩子文案 → 中 1/3 产品主视觉 → 下 1/3 价格+CTA，转化组件底部居中。",
    content:
      "构图层级：\n1. 顶部：钩子/活动标题\n2. 中部：产品 hero + 场景\n3. 底部：券后价 + CTA 按钮\n\n角标左上，LOGO 右上。",
    tags: ["构图", "外投图", "转化"],
    visibility: "team",
    status: "active",
    createdBy: "设计-小王",
    createdAt: "2026-04-20 10:00",
    updatedAt: "2026-05-01 14:00",
    usageCount: 267,
    version: 2,
  },
  {
    id: "kn-15",
    title: "15 秒带货短视频四段式脚本范式",
    topCategory: "structure-paradigm",
    subTopicId: "video-script",
    channels: ["douyin", "channels"],
    industries: ["all"],
    priority: "high",
    summary: "钩子(0–3s) → 卖点(3–11s) → 价格(11–13s) → CTA(13–15s)。",
    content:
      "**钩子 0–3s**：痛点提问或反差开场\n**卖点 3–11s**：3 个核心卖点，每 2–3s 一切\n**价格 11–13s**：券后价弹出 + 音效\n**CTA 13–15s**：立即领券 / 下单引导",
    tags: ["15s", "脚本", "四段式"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小李",
    createdAt: "2026-05-01 09:00",
    updatedAt: "2026-06-10 11:00",
    usageCount: 312,
    version: 4,
  },
  {
    id: "kn-16",
    title: "CTA 组件设计通用规范",
    topCategory: "structure-paradigm",
    subTopicId: "cta-design",
    channels: ["all"],
    industries: ["all"],
    priority: "medium",
    summary: "按钮宽度 ≥ 画面 60%，文案 ≤6 字，高对比色，距底边 ≥ 8% 安全区。",
    content: "CTA 文案推荐：立即领券、马上抢购、查看详情。按钮圆角 8px，主色填充 + 白字。",
    tags: ["CTA", "转化", "组件"],
    visibility: "public",
    status: "active",
    createdBy: "系统",
    createdAt: "2026-01-15 00:00",
    updatedAt: "2026-01-15 00:00",
    usageCount: 445,
    version: 1,
  },
  {
    id: "kn-17",
    title: "高点击率素材成功经验 · 省钱券",
    topCategory: "review-insights",
    subTopicId: "success-cases",
    channels: ["douyin"],
    industries: ["all"],
    priority: "medium",
    summary: "真实厨房场景 + 券后价大字 + 「比日常省 XX 元」结构，CTR 提升 35%。",
    content: "复盘结论：生活化场景比纯色底 CTR 高 35%；券后价需与划线价同屏对比。",
    tags: ["复盘", "高点击", "省钱券"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小李",
    createdAt: "2026-06-15 16:00",
    updatedAt: "2026-06-15 16:00",
    usageCount: 23,
    version: 1,
  },
  {
    id: "kn-18",
    title: "低效素材踩坑 · 过度促销红",
    topCategory: "review-insights",
    subTopicId: "failure-cases",
    channels: ["douyin"],
    industries: ["beauty"],
    priority: "low",
    summary: "全屏促销红 + 多角标堆叠导致审核驳回与用户跳过率上升。",
    content: "踩坑记录：美妆品类全屏大红底审核通过率下降 40%，建议保留 30% 以上产品展示面积。",
    tags: ["踩坑", "低效", "美妆"],
    visibility: "private",
    status: "active",
    createdBy: "当前用户",
    createdAt: "2026-06-18 10:00",
    updatedAt: "2026-06-18 10:00",
    usageCount: 5,
    version: 1,
  },
  {
    id: "kn-19",
    title: "A/B 测试 · 钩子开场类型对比",
    topCategory: "review-insights",
    subTopicId: "ab-conclusions",
    channels: ["douyin"],
    industries: ["food"],
    priority: "medium",
    summary: "痛点提问开场比产品直给开场 CTR 高 22%，但完播率低 8%。",
    content: "A 组：痛点提问；B 组：产品直给。CTR +22%，完播率 -8%。食品类建议痛点开场 + 快速切入产品。",
    tags: ["A/B", "钩子", "食品"],
    visibility: "team",
    status: "disabled",
    createdBy: "运营-小张",
    createdAt: "2026-06-10 14:00",
    updatedAt: "2026-06-12 09:00",
    usageCount: 12,
    version: 2,
  },
  {
    id: "kn-20",
    title: "小红书笔记封面构图偏好",
    topCategory: "channel-rules",
    subTopicId: "channel-preference",
    channels: ["xiaohongshu"],
    industries: ["beauty", "food"],
    priority: "medium",
    summary: "3:4 竖版，大留白 + 手写体标题，低饱和滤镜更契合平台调性。",
    content: "封面偏好：产品占 40%，其余留白放标题。避免过多促销元素，强调「种草感」。",
    tags: ["小红书", "封面", "偏好"],
    visibility: "team",
    status: "active",
    createdBy: "运营-小张",
    createdAt: "2026-06-08 11:00",
    updatedAt: "2026-06-08 11:00",
    usageCount: 34,
    version: 1,
  },
];

export function queryKnowledgeEntries(params: {
  search?: string;
  topCategory?: KnowledgeEntry["topCategory"] | "all";
  channel?: string;
  industry?: string;
  status?: KnowledgeEntry["status"] | "all";
  visibility?: KnowledgeEntry["visibility"] | "all" | "mine";
}): KnowledgeEntry[] {
  const { search, topCategory, channel, industry, status, visibility } = params;

  return KNOWLEDGE_ENTRIES.filter((e) => {
    if (topCategory && topCategory !== "all" && e.topCategory !== topCategory) return false;
    if (channel && channel !== "all" && !e.channels.includes(channel) && !e.channels.includes("all"))
      return false;
    if (industry && industry !== "all" && !e.industries.includes(industry) && !e.industries.includes("all"))
      return false;
    if (status && status !== "all" && e.status !== status) return false;
    if (visibility === "mine" && e.createdBy !== "当前用户" && e.visibility !== "private") return false;
    if (visibility && visibility !== "all" && visibility !== "mine" && e.visibility !== visibility) return false;

    if (search?.trim()) {
      const q = search.trim().toLowerCase();
      const hay = [e.title, e.summary, ...e.tags, ...e.channels, ...e.industries].join(" ").toLowerCase();
      if (!hay.includes(q)) return false;
    }

    return true;
  });
}
