import type { AssetOwnership, MaterialCatalogAsset } from "./catalog-types";

const PREVIEW_COLORS = [
  "#E0E7FF", "#FEE2E2", "#D1FAE5", "#FEF3C7", "#DBEAFE", "#F3E8FF",
  "#FFEDD5", "#E5E7EB", "#6366F1", "#14B8A6", "#F97316", "#8B5CF6",
];

function pickColor(i: number) {
  return PREVIEW_COLORS[i % PREVIEW_COLORS.length];
}

/** 素材库完整 mock 资产列表 */
export const MATERIAL_CATALOG_ASSETS: MaterialCatalogAsset[] = [
  // ── 品牌专属 ──
  {
    id: "mc-brand-1",
    name: "品牌横版 LOGO · 主色",
    tab: "image",
    topCategory: "brand",
    subCategoryId: "logo",
    ownership: "team",
    source: "uploaded",
    tags: ["LOGO", "横版", "主色"],
    previewColor: "#1E3A5F",
    createdAt: "2026-05-10 09:00",
    createdBy: "品牌管理员",
    usageCount: 128,
    usageRecords: [
      { taskName: "618 主图批量生成", usedAt: "2026-06-18 14:20" },
      { taskName: "抖音信息流封面", usedAt: "2026-06-15 10:05" },
    ],
    materialType: "image",
    fileSize: "256 KB",
    width: 1200,
    height: 400,
  },
  {
    id: "mc-brand-2",
    name: "反白 LOGO · 深色底专用",
    tab: "image",
    topCategory: "brand",
    subCategoryId: "logo",
    ownership: "team",
    source: "uploaded",
    tags: ["LOGO", "反白"],
    previewColor: "#111827",
    createdAt: "2026-05-10 09:05",
    createdBy: "品牌管理员",
    usageCount: 86,
    usageRecords: [{ taskName: "夜间版外投图", usedAt: "2026-06-12 16:30" }],
    materialType: "image",
    fileSize: "198 KB",
  },
  {
    id: "mc-brand-3",
    name: "618 品牌主 KV",
    tab: "image",
    topCategory: "brand",
    subCategoryId: "brand-visual",
    ownership: "team",
    source: "ai-generated",
    tags: ["KV", "618", "大促"],
    previewColor: "#FF0036",
    createdAt: "2026-05-28 11:00",
    createdBy: "运营-小李",
    usageCount: 45,
    usageRecords: [],
    materialType: "image",
    fileSize: "1.2 MB",
    width: 1920,
    height: 1080,
  },
  {
    id: "mc-brand-4",
    name: "官方指定字体包 · 思源黑体",
    tab: "image",
    topCategory: "brand",
    subCategoryId: "brand-font",
    ownership: "public",
    source: "system",
    tags: ["字体", "官方"],
    previewColor: "#374151",
    createdAt: "2026-01-01 00:00",
    createdBy: "系统",
    usageCount: 520,
    usageRecords: [],
    materialType: "font",
    fileSize: "8.5 MB",
    readonly: true,
  },
  {
    id: "mc-brand-5",
    name: "品牌固定排版模板 · 促销版",
    tab: "image",
    topCategory: "brand",
    subCategoryId: "brand-layout",
    ownership: "team",
    source: "uploaded",
    tags: ["版式", "促销"],
    previewColor: "#DBEAFE",
    createdAt: "2026-04-15 14:00",
    createdBy: "设计-小王",
    usageCount: 67,
    usageRecords: [],
    materialType: "template",
    fileSize: "420 KB",
  },
  // ── 图片链路 ──
  {
    id: "mc-img-1",
    name: "省钱神券 · 抖音信息流外投图",
    tab: "image",
    topCategory: "image-pipeline",
    subCategoryId: "finished-image",
    ownership: "private",
    source: "ai-generated",
    tags: ["省钱券", "抖音", "信息流"],
    previewColor: "#FEE2E2",
    createdAt: "2026-06-18 15:30",
    createdBy: "当前用户",
    usageCount: 12,
    usageRecords: [{ taskName: "省钱神券外投", usedAt: "2026-06-18 15:35" }],
    materialType: "image",
    fileSize: "890 KB",
    width: 1080,
    height: 1920,
  },
  {
    id: "mc-img-2",
    name: "商品主图 · 防晒喷雾 800×800",
    tab: "image",
    topCategory: "image-pipeline",
    subCategoryId: "finished-image",
    ownership: "private",
    source: "ai-generated",
    tags: ["主图", "美妆", "防晒"],
    previewColor: "#FEF3C7",
    createdAt: "2026-06-17 10:00",
    createdBy: "当前用户",
    usageCount: 8,
    usageRecords: [],
    materialType: "image",
    fileSize: "650 KB",
    width: 800,
    height: 800,
  },
  {
    id: "mc-img-3",
    name: "暖色厨房场景底图",
    tab: "image",
    topCategory: "image-pipeline",
    subCategoryId: "visual-base",
    ownership: "team",
    source: "uploaded",
    tags: ["背景", "厨房", "暖光"],
    previewColor: "#FBBF24",
    createdAt: "2026-05-20 09:00",
    createdBy: "运营-小张",
    usageCount: 34,
    usageRecords: [],
    materialType: "image",
    fileSize: "2.1 MB",
  },
  {
    id: "mc-img-4",
    name: "「限时捡漏」促销角标",
    tab: "image",
    topCategory: "image-pipeline",
    subCategoryId: "marketing-component",
    ownership: "team",
    source: "uploaded",
    tags: ["角标", "捡漏", "促销"],
    previewColor: "#DC2626",
    createdAt: "2026-06-01 11:00",
    createdBy: "运营-小李",
    usageCount: 91,
    usageRecords: [],
    materialType: "image",
    fileSize: "45 KB",
  },
  {
    id: "mc-img-5",
    name: "券后价标签模板",
    tab: "image",
    topCategory: "image-pipeline",
    subCategoryId: "marketing-component",
    ownership: "private",
    source: "ai-generated",
    tags: ["价格标签", "券后价"],
    previewColor: "#FF0036",
    createdAt: "2026-06-10 16:00",
    createdBy: "当前用户",
    usageCount: 23,
    usageRecords: [],
    materialType: "template",
    fileSize: "120 KB",
  },
  {
    id: "mc-img-6",
    name: "外投图整套配置 · 省钱券中心",
    tab: "image",
    topCategory: "image-pipeline",
    subCategoryId: "image-config-template",
    ownership: "private",
    source: "ai-generated",
    tags: ["配置模板", "省钱券", "一键填充"],
    previewColor: "#E0E7FF",
    createdAt: "2026-06-19 09:00",
    createdBy: "当前用户",
    usageCount: 5,
    usageRecords: [],
    materialType: "config",
    fileSize: "18 KB",
  },
  {
    id: "mc-img-7",
    name: "领券引导短句 · 捡漏专场",
    tab: "image",
    topCategory: "image-pipeline",
    subCategoryId: "copy-template",
    ownership: "team",
    source: "uploaded",
    tags: ["文案", "领券", "捡漏"],
    previewColor: "#D1FAE5",
    createdAt: "2026-06-05 14:00",
    createdBy: "运营-小李",
    usageCount: 56,
    usageRecords: [],
    materialType: "copy",
    fileSize: "2 KB",
  },
  // ── 视频链路 ──
  {
    id: "mc-vid-1",
    name: "15s 带货成片 · 防晒喷雾",
    tab: "video",
    topCategory: "video-pipeline",
    subCategoryId: "finished-video",
    ownership: "private",
    source: "ai-generated",
    tags: ["成片", "15s", "带货"],
    previewColor: "#6366F1",
    durationSec: 15,
    createdAt: "2026-06-16 17:00",
    createdBy: "当前用户",
    usageCount: 6,
    usageRecords: [{ taskName: "防晒短视频投放", usedAt: "2026-06-16 17:10" }],
    materialType: "video",
    fileSize: "12.5 MB",
  },
  {
    id: "mc-vid-2",
    name: "钩子镜头 · 痛点提问开场",
    tab: "video",
    topCategory: "video-pipeline",
    subCategoryId: "clip-fragments",
    ownership: "team",
    source: "uploaded",
    tags: ["钩子", "开场", "3s"],
    previewColor: "#EF4444",
    durationSec: 3,
    createdAt: "2026-05-25 10:00",
    createdBy: "运营-小张",
    usageCount: 42,
    usageRecords: [],
    materialType: "video",
    fileSize: "2.8 MB",
  },
  {
    id: "mc-vid-3",
    name: "卖点镜头 · 功效可视化",
    tab: "video",
    topCategory: "video-pipeline",
    subCategoryId: "clip-fragments",
    ownership: "team",
    source: "uploaded",
    tags: ["卖点", "功效"],
    previewColor: "#14B8A6",
    durationSec: 8,
    createdAt: "2026-05-25 10:05",
    createdBy: "运营-小张",
    usageCount: 38,
    usageRecords: [],
    materialType: "video",
    fileSize: "5.2 MB",
  },
  {
    id: "mc-vid-4",
    name: "快节奏电子 BGM · 120BPM",
    tab: "video",
    topCategory: "video-pipeline",
    subCategoryId: "audio",
    ownership: "public",
    source: "system",
    tags: ["BGM", "卡点", "电子"],
    previewColor: "#8B5CF6",
    durationSec: 60,
    createdAt: "2026-01-01 00:00",
    createdBy: "系统",
    usageCount: 890,
    usageRecords: [],
    materialType: "audio",
    fileSize: "4.5 MB",
    readonly: true,
  },
  {
    id: "mc-vid-5",
    name: "活力女声口播 · 带货专用",
    tab: "video",
    topCategory: "video-pipeline",
    subCategoryId: "audio",
    ownership: "private",
    source: "ai-generated",
    tags: ["口播", "女声", "带货"],
    previewColor: "#EC4899",
    durationSec: 45,
    createdAt: "2026-06-14 11:00",
    createdBy: "当前用户",
    usageCount: 15,
    usageRecords: [],
    materialType: "audio",
    fileSize: "1.8 MB",
  },
  {
    id: "mc-vid-6",
    name: "缩放转场方案 · 产品特写",
    tab: "video",
    topCategory: "video-pipeline",
    subCategoryId: "transition-template",
    ownership: "team",
    source: "uploaded",
    tags: ["转场", "缩放"],
    previewColor: "#0EA5E9",
    createdAt: "2026-05-18 09:00",
    createdBy: "设计-小王",
    usageCount: 72,
    usageRecords: [],
    materialType: "template",
    fileSize: "85 KB",
  },
  {
    id: "mc-vid-7",
    name: "15s 四段式视频配置模板",
    tab: "video",
    topCategory: "video-pipeline",
    subCategoryId: "video-config-template",
    ownership: "private",
    source: "ai-generated",
    tags: ["配置模板", "四段式", "15s"],
    previewColor: "#7C3AED",
    createdAt: "2026-06-19 10:00",
    createdBy: "当前用户",
    usageCount: 3,
    usageRecords: [],
    materialType: "config",
    fileSize: "22 KB",
  },
  // ── 业务策略 ──
  {
    id: "mc-str-1",
    name: "省钱神券中心 · 投放需求模板",
    tab: "image",
    topCategory: "strategy",
    subCategoryId: "demand-template",
    ownership: "team",
    source: "ai-generated",
    tags: ["投放需求", "省钱券", "结构化"],
    previewColor: "#F97316",
    createdAt: "2026-06-10 09:00",
    createdBy: "运营-小李",
    usageCount: 28,
    usageRecords: [],
    materialType: "config",
    fileSize: "15 KB",
  },
  {
    id: "mc-str-2",
    name: "捡漏专场 · 选品策略模板",
    tab: "image",
    topCategory: "strategy",
    subCategoryId: "selection-strategy",
    ownership: "team",
    source: "uploaded",
    tags: ["选品", "捡漏", "低价"],
    previewColor: "#FBBF24",
    createdAt: "2026-06-08 14:00",
    createdBy: "运营-小张",
    usageCount: 19,
    usageRecords: [],
    materialType: "config",
    fileSize: "8 KB",
  },
  {
    id: "mc-str-3",
    name: "618 美妆爆款商品分组",
    tab: "image",
    topCategory: "strategy",
    subCategoryId: "product-group",
    ownership: "private",
    source: "uploaded",
    tags: ["商品分组", "618", "美妆"],
    previewColor: "#FCE7F3",
    createdAt: "2026-06-01 10:00",
    createdBy: "当前用户",
    usageCount: 11,
    usageRecords: [],
    materialType: "config",
    fileSize: "12 KB",
  },
  {
    id: "mc-str-4",
    name: "短视频带货 · 投放需求模板",
    tab: "video",
    topCategory: "strategy",
    subCategoryId: "demand-template",
    ownership: "team",
    source: "ai-generated",
    tags: ["投放需求", "短视频"],
    previewColor: "#A5B4FC",
    createdAt: "2026-06-12 11:00",
    createdBy: "运营-小李",
    usageCount: 14,
    usageRecords: [],
    materialType: "config",
    fileSize: "14 KB",
  },
  // ── 平台公共 ──
  {
    id: "mc-pub-1",
    name: "通用渐变背景 · 蓝紫",
    tab: "image",
    topCategory: "platform-public",
    subCategoryId: "system-preset",
    ownership: "public",
    source: "system",
    tags: ["背景", "系统预置"],
    previewColor: "#6366F1",
    createdAt: "2026-01-01 00:00",
    createdBy: "系统",
    usageCount: 1200,
    usageRecords: [],
    materialType: "image",
    fileSize: "320 KB",
    readonly: true,
  },
  {
    id: "mc-pub-2",
    name: "「爆款」通用促销角标",
    tab: "image",
    topCategory: "platform-public",
    subCategoryId: "system-preset",
    ownership: "public",
    source: "system",
    tags: ["角标", "爆款", "系统预置"],
    previewColor: "#DC2626",
    createdAt: "2026-01-01 00:00",
    createdBy: "系统",
    usageCount: 980,
    usageRecords: [],
    materialType: "image",
    fileSize: "38 KB",
    readonly: true,
  },
  {
    id: "mc-pub-3",
    name: "轻音乐氛围 BGM",
    tab: "video",
    topCategory: "platform-public",
    subCategoryId: "system-preset",
    ownership: "public",
    source: "system",
    tags: ["BGM", "轻音乐", "系统预置"],
    previewColor: "#A5B4FC",
    durationSec: 90,
    createdAt: "2026-01-01 00:00",
    createdBy: "系统",
    usageCount: 650,
    usageRecords: [],
    materialType: "audio",
    fileSize: "3.8 MB",
    readonly: true,
  },
  {
    id: "mc-pub-4",
    name: "抖音信息流 · 1080×1920 尺寸参考",
    tab: "image",
    topCategory: "platform-public",
    subCategoryId: "channel-size",
    ownership: "public",
    source: "system",
    tags: ["抖音", "尺寸", "竖版"],
    previewColor: "#E5E7EB",
    createdAt: "2026-01-01 00:00",
    createdBy: "系统",
    usageCount: 430,
    usageRecords: [],
    materialType: "template",
    fileSize: "5 KB",
    width: 1080,
    height: 1920,
    readonly: true,
  },
  {
    id: "mc-pub-5",
    name: "小红书笔记封面 · 3:4 尺寸参考",
    tab: "image",
    topCategory: "platform-public",
    subCategoryId: "channel-size",
    ownership: "public",
    source: "system",
    tags: ["小红书", "尺寸", "3:4"],
    previewColor: "#FEE2E2",
    createdAt: "2026-01-01 00:00",
    createdBy: "系统",
    usageCount: 310,
    usageRecords: [],
    materialType: "template",
    fileSize: "5 KB",
    width: 1080,
    height: 1440,
    readonly: true,
  },
];

/** 补充若干带颜色的占位资产，便于列表展示 */
for (let i = 0; i < 8; i++) {
  const isVideo = i % 3 === 0;
  MATERIAL_CATALOG_ASSETS.push({
    id: `mc-gen-${i}`,
    name: isVideo ? `镜头素材片段 #${i + 1}` : `视觉素材 #${i + 1}`,
    tab: isVideo ? "video" : "image",
    topCategory: isVideo ? "video-pipeline" : "image-pipeline",
    subCategoryId: isVideo ? "clip-fragments" : "visual-base",
    ownership: i % 2 === 0 ? "private" : "team",
    source: i % 4 === 0 ? "ai-generated" : "uploaded",
    tags: ["批量", "示例"],
    previewColor: pickColor(i),
    createdAt: `2026-06-${String(10 + i).padStart(2, "0")} 12:00`,
    createdBy: i % 2 === 0 ? "当前用户" : "运营-小张",
    usageCount: Math.floor(Math.random() * 30),
    usageRecords: [],
    materialType: isVideo ? "video" : "image",
    fileSize: `${200 + i * 50} KB`,
    durationSec: isVideo ? 5 + i : undefined,
  });
}

export function queryMaterialCatalog(params: {
  tab: "image" | "video";
  search?: string;
  ownership?: AssetOwnership | "all";
  topCategory?: MaterialCatalogAsset["topCategory"] | "all";
  subCategoryId?: string;
  source?: MaterialCatalogAsset["source"] | "all";
  dateFrom?: string;
  dateTo?: string;
}): MaterialCatalogAsset[] {
  const { tab, search, ownership, topCategory, subCategoryId, source, dateFrom, dateTo } = params;

  return MATERIAL_CATALOG_ASSETS.filter((a) => {
    if (a.tab !== tab && a.topCategory !== "brand" && a.topCategory !== "strategy" && a.topCategory !== "platform-public") {
      return false;
    }
    if (tab === "image" && a.topCategory === "video-pipeline") return false;
    if (tab === "video" && a.topCategory === "image-pipeline") return false;

    if (ownership && ownership !== "all" && a.ownership !== ownership) return false;
    if (topCategory && topCategory !== "all" && a.topCategory !== topCategory) return false;
    if (subCategoryId && a.subCategoryId !== subCategoryId) return false;
    if (source && source !== "all" && a.source !== source) return false;

    if (dateFrom && a.createdAt < dateFrom) return false;
    if (dateTo && a.createdAt > dateTo + " 23:59") return false;

    if (search?.trim()) {
      const q = search.trim().toLowerCase();
      const hay = [a.name, ...a.tags, a.createdBy].join(" ").toLowerCase();
      if (!hay.includes(q)) return false;
    }

    return true;
  });
}
