import type { LibraryAsset } from "./types";

/** 系统公共素材库（预置） */
export const PUBLIC_LIBRARY_ASSETS: LibraryAsset[] = [
  {
    id: "pub-bg-001",
    name: "电商通透渐变背景",
    scope: "public",
    category: "visual",
    subCategory: "background",
    materialType: "image",
    url: "/placeholder/material-1.jpg",
    thumbnailUrl: "/placeholder/material-1.jpg",
    tags: ["背景", "渐变", "电商"],
    sourceChain: "both",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-bg-002",
    name: "国潮纹理背景",
    scope: "public",
    category: "visual",
    subCategory: "background",
    materialType: "image",
    url: "/placeholder/material-2.jpg",
    thumbnailUrl: "/placeholder/material-2.jpg",
    tags: ["背景", "国潮"],
    sourceChain: "both",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-comp-001",
    name: "居中主体构图模板",
    scope: "public",
    category: "param-template",
    subCategory: "composition",
    tags: ["构图", "居中"],
    configJson: JSON.stringify({ layout: "center", padding: 12 }),
    sourceChain: "image",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-style-001",
    name: "写实高清风格包",
    scope: "public",
    category: "param-template",
    subCategory: "style",
    tags: ["写实", "高清"],
    configJson: JSON.stringify({ visualStyle: "写实高清", lighting: "自然日光" }),
    sourceChain: "both",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-badge-001",
    name: "限时角标",
    scope: "public",
    category: "visual",
    subCategory: "badge",
    tags: ["角标", "限时"],
    sourceChain: "both",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-badge-002",
    name: "热销跳动标签",
    scope: "public",
    category: "visual",
    subCategory: "badge",
    tags: ["角标", "热销"],
    sourceChain: "video",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-bgm-001",
    name: "节奏感带货 BGM",
    scope: "public",
    category: "audio",
    subCategory: "bgm",
    materialType: "video",
    url: "/placeholder/audio-1.mp3",
    tags: ["BGM", "快节奏"],
    sourceChain: "video",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-sfx-001",
    name: "卡点鼓点音效包",
    scope: "public",
    category: "audio",
    subCategory: "sfx",
    tags: ["音效", "卡点"],
    sourceChain: "video",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-copy-001",
    name: "领券省钱标题模板",
    scope: "public",
    category: "copy",
    tags: ["文案", "领券", "省钱"],
    configJson: JSON.stringify({ mainTitle: "领券后更划算", subLines: ["限时特惠", "爆款直降"] }),
    sourceChain: "both",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-trans-001",
    name: "闪白硬切转场",
    scope: "public",
    category: "param-template",
    subCategory: "transition",
    tags: ["转场", "硬切"],
    configJson: JSON.stringify({ type: "flash-cut", duration: 0.2 }),
    sourceChain: "video",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-sub-001",
    name: "逐字弹出字幕动画",
    scope: "public",
    category: "param-template",
    subCategory: "subtitle-animation",
    tags: ["字幕", "动画"],
    configJson: JSON.stringify({ animation: "typewriter" }),
    sourceChain: "video",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "pub-filter-001",
    name: "电商通透滤镜",
    scope: "public",
    category: "param-template",
    subCategory: "filter",
    tags: ["滤镜", "通透"],
    configJson: JSON.stringify({ brightness: 1.05, contrast: 1.1, saturation: 1.08 }),
    sourceChain: "both",
    createdAt: "2025-01-01T00:00:00Z",
  },
];

/** 个人私有素材库（演示） */
export const PRIVATE_LIBRARY_ASSETS: LibraryAsset[] = [
  {
    id: "pri-bg-001",
    name: "我的品牌蓝渐变背景",
    scope: "private",
    category: "visual",
    subCategory: "background",
    materialType: "image",
    url: "/placeholder/material-3.jpg",
    thumbnailUrl: "/placeholder/material-3.jpg",
    tags: ["背景", "品牌色"],
    sourceChain: "both",
    createdAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "pri-ref-001",
    name: "空气炸锅实拍参考图",
    scope: "private",
    category: "visual",
    subCategory: "reference",
    materialType: "image",
    url: "/placeholder/material-4.jpg",
    thumbnailUrl: "/placeholder/material-4.jpg",
    tags: ["商品", "参考图"],
    sourceChain: "image",
    createdAt: "2025-06-10T00:00:00Z",
  },
  {
    id: "pri-clip-001",
    name: "钩子镜头片段 3s",
    scope: "private",
    category: "visual",
    subCategory: "video-clip",
    materialType: "video",
    url: "/placeholder/video-clip-1.mp4",
    tags: ["镜头", "钩子"],
    sourceChain: "video",
    createdAt: "2025-06-12T00:00:00Z",
  },
  {
    id: "pri-copy-001",
    name: "省钱捡漏卖点文案包",
    scope: "private",
    category: "copy",
    tags: ["文案", "省钱", "捡漏"],
    configJson: JSON.stringify({
      mainTitle: "领券后更划算",
      sellingPoints: ["高性价比", "限时捡漏", "正品保障"],
    }),
    sourceChain: "both",
    createdAt: "2025-06-15T00:00:00Z",
  },
  {
    id: "pri-color-001",
    name: "品牌专属配色方案",
    scope: "private",
    category: "param-template",
    subCategory: "color-scheme",
    tags: ["配色", "品牌"],
    configJson: JSON.stringify({ primary: "#FF4D4F", accent: "#FFD666", text: "#1A1A1A" }),
    sourceChain: "both",
    createdAt: "2025-06-16T00:00:00Z",
  },
  {
    id: "pri-typo-001",
    name: "大标题排版模板",
    scope: "private",
    category: "param-template",
    subCategory: "typography",
    tags: ["字体", "排版"],
    configJson: JSON.stringify({ fontFamily: "PingFang SC", titleSize: 48, align: "center" }),
    sourceChain: "image",
    createdAt: "2025-06-17T00:00:00Z",
  },
];

export const ALL_LIBRARY_ASSETS = [...PRIVATE_LIBRARY_ASSETS, ...PUBLIC_LIBRARY_ASSETS];
